import { useState } from "react";
import "../styles/help.css";

function FAQItem({ question, answer }) {

  const [open, setOpen] = useState(false);

  return (
    <div className="faq-item">
      <button
        className="faq-question"
        onClick={() => setOpen(!open)}
      >
        <span>{question}</span>
        <span>
          {open ? "−" : "+"}
        </span>
      </button>
      {open && (
        <div className="faq-answer">
          <p>{answer}</p>
        </div>
      )}
    </div>
  );

}

function Help() {
  return (
    <div className="help-page">

      <h1>Help & User Guide</h1>

      <p className="help-intro">
        ParaVirPred is an AI-powered parasite virulence prediction platform
        that uses Protein Language Models (ESM2 and ProtT5), physicochemical
        descriptors, and machine learning models to identify virulence-associated
        proteins from protein sequences and FASTA datasets.
      </p>

      {/* Step Guide */}

      <section className="help-section">

        <h2>Step-by-Step Usage Guide</h2>

        <div className="help-card">

          <h3>Step 1: Open Prediction Page</h3>

          <p>
            Navigate to the Prediction page from the top navigation menu.
          </p>

        </div>

        <div className="help-card">

          <h3>Step 2: Provide Input Sequence(s)</h3>

          <p>
            You may either:
          </p>

          <ul>
            <li>Paste a single protein sequence.</li>
            <li>Paste multiple FASTA sequences.</li>
            <li>Upload a FASTA file.</li>
          </ul>

        </div>

        <div className="help-card">

          <h3>Step 3: Select Model Combination</h3>

          <p>
            Choose one of the available trained models from the dropdown menu.
          </p>

        </div>

        <div className="help-card">

          <h3>Step 4: Run Prediction</h3>

          <p>
            Click the <strong>Predict Virulence</strong> button.
            The system will process the sequences and return predictions.
          </p>

        </div>

        <div className="help-card">

          <h3>Step 5: Review Results</h3>

          <p>
            The results table displays:
          </p>

          <ul>
            <li>Sequence ID</li>
            <li>Predicted Class</li>
            <li>Prediction Probability</li>
          </ul>

        </div>

        <div className="help-card">

          <h3>Step 6: Download Results</h3>

          <p>
            Click the Download CSV button to export prediction results.
          </p>

        </div>

      </section>

      {/* Input Examples */}

      <section className="help-section">

        <h2>Input Format Examples</h2>

        <div className="help-example">

<pre>
{`Single Sequence:

MKTLLVVAAATTTGGGCCCAAATTTGGG
`}
</pre>

        </div>

        <div className="help-example">

<pre>
{`Multiple FASTA Sequences:

>Protein_1
MKTLLVVAAATTTGGG

>Protein_2
AAATTTCCCGGGAAA
`}
</pre>

        </div>

      </section>

      {/* Models */}

      <section className="help-section">

        <h2>Available Model Combinations</h2>

        <ul className="model-list">

          <li>ESM2 Only</li>

          <li>ESM2 + PhysChem</li>

          <li>ProtT5 Only</li>

          <li>ProtT5 + PhysChem</li>

          <li>ESM2 + ProtT5</li>

          <li>ESM2 + ProtT5 + PhysChem</li>

        </ul>

        <p>
          Different models capture different biological properties.
          Combined models generally provide improved predictive performance.
        </p>

      </section>

      {/* Results */}

      <section className="help-section">

        <h2>Understanding Prediction Results</h2>

        <ul>

          <li>
            <strong>Virulent</strong> →
            Protein is predicted to contribute to pathogen virulence.
          </li>

          <li>
            <strong>Non-Virulent</strong> →
            Protein is unlikely to be involved in virulence mechanisms.
          </li>

          <li>
            <strong>Probability Score</strong> →
            Confidence score generated by the machine learning model.
          </li>

        </ul>

      </section>

      <section className="help-section">

        <h2>Frequently Asked Questions (FAQ)</h2>

        <FAQItem
          question="What types of sequences are supported?"
          answer="Protein sequences composed of standard amino acids in plain sequence or FASTA format."
        />

        <FAQItem
          question="Can I upload multiple proteins simultaneously?"
          answer="Yes. Multi-sequence FASTA files are fully supported and can be processed in batch mode."
        />

        <FAQItem
          question="Which model should I use?"
          answer="For highest performance we recommend ProtT5 + PhysChem or ESM2 + ProtT5 + PhysChem combinations."
        />

        <FAQItem
          question="How large can my FASTA file be?"
          answer="Upload limits are enforced to maintain server performance. Refer to the Prediction page for current limits."
        />

        <FAQItem
          question="Can I use the models locally?"
          answer="Yes. Trained models, benchmark datasets, and standalone prediction scripts can be downloaded from the Download page."
        />

        <FAQItem
          question="Are the predictions experimentally validated?"
          answer="Predictions are generated using machine learning models trained on curated benchmark datasets. Experimental validation is recommended before downstream biological applications."
        />

        <FAQItem
          question="What should I do if my prediction fails?"
          answer="Verify that the sequence contains valid amino acids and that the FASTA format is correct. If the issue persists, contact the development team."
        />

      </section>

    </div>
  );
}

export default Help;